### PR TITLE
Web fixups

### PR DESCRIPTION
**Pull request by danielgustafsson**
A few assorted fixes to improve HTML validation, remove past events and fix typos.

### CODE REVIEW

**Comment by xinzweb** [comment]
+1

**Comment by danielgustafsson** [comment]
Thanks for review. Do you know if the page will be automatically refreshed upon pushing the commits?

**Comment by xinzweb** [comment]
I believe so.

**Comment by ivannovick** [comment]
@rvs can you commit this?

**Comment by danielgustafsson** [comment]
Pushed, thanks for review.

**Pull request closed without merging**
