### PR TITLE
Remove javascript from website

### PR DESCRIPTION
**Pull request by danielgustafsson**
The Javascript files don't add any value to the page, smooth scroll, new-tab on links, and equal size event divs are hardly worth the load + parse + execute time. Remove and set href target manually until we need more interactivity.

### CODE REVIEW

**Comment by schubert** [comment]
Can you rebase?

**Comment by danielgustafsson** [comment]
Pushed a rebased version.

**Comment by rvs** [comment]
@danielgustafsson I've just noticed this one outstanding. Sorry to ask for one more rebase: but any chance you can do it so we can merge this in?

**Comment by danielgustafsson** [comment]
Rebased on top of master. If this is considered worthwhile it's ready to be pushed.

**Comment by rvs** [comment]
Merged manually

**Pull request closed without merging**
